import { UserRole, PaymentVoucher, VendorQuote, PeachtreeEntry, ClientMilestoneContract, TaxDeclaration } from './types';

export const ROLES: Record<string, UserRole> = {
  mesael: {
    id: 'mesael',
    name: 'Mesael',
    avatar: 'MS',
    title: 'Owner / CEO',
    tagline: 'Owner workspace — reserved approvals & high-level reporting',
  },
  dembi: {
    id: 'dembi',
    name: 'Dembi',
    avatar: 'DG',
    title: 'Deputy GM & Finance Head',
    tagline: 'Delegated approvals (up to ETB 500k), fund health & cash accounts',
  },
  leta: {
    id: 'leta',
    name: 'Leta',
    avatar: 'LG',
    title: 'Operational Finance',
    tagline: 'Voucher preparation, vendor comparisons & petty cash floats',
  },
  kalkidan: {
    id: 'kalkidan',
    name: 'Kalkidan',
    avatar: 'KA',
    title: 'Accountant',
    tagline: 'Ledger reconciliation & Peachtree staged export queue',
  },
  yamrot: {
    id: 'yamrot',
    name: 'Yamrot',
    avatar: 'YB',
    title: 'Billing & Tax',
    tagline: 'Client milestone billing, tax clearance tracking & VAT filings',
  },
};

export const INITIAL_VOUCHERS: PaymentVoucher[] = [
  {
    id: '1',
    code: 'PV-2026-00481',
    title: 'Rebar delivery — Bole Ring Road',
    project: 'Bole Ring Road Extension',
    costCode: 'CC-2201 · Reinforcement steel',
    payee: 'Selam Steel PLC',
    amount: 286400,
    method: 'RTGS',
    status: 'ready_for_approval',
    preparedBy: 'Leta Girma',
    assignedApprover: 'dembi',
    docsCount: 4,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: true, grn: true, taxInvoice: true },
    budgetBefore: 612900,
    budgetAfter: 326500,
    date: '2026-08-05',
  },
  {
    id: '2',
    code: 'PV-2026-00479',
    title: 'Subcontractor advance — CMC Residential Ph.2',
    project: 'CMC Residential Phase 2',
    costCode: 'CC-4102 · Concrete Works',
    payee: 'Girum Concrete Works',
    amount: 1150000,
    method: 'RTGS',
    status: 'owner_reserved',
    preparedBy: 'Leta Girma',
    assignedApprover: 'mesael',
    docsCount: 4,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: true, grn: true, taxInvoice: true },
    budgetBefore: 2400000,
    budgetAfter: 1250000,
    date: '2026-08-03',
  },
  {
    id: '3',
    code: 'PV-2026-00477',
    title: 'Formwork timber — Adama Logistics Park',
    project: 'Adama Logistics Park',
    costCode: 'CC-3011 · Formwork & Shoring',
    payee: 'Oda Timber & Hardware',
    amount: 118650,
    method: 'Cheque',
    status: 'ready_for_approval',
    preparedBy: 'Leta Girma',
    assignedApprover: 'dembi',
    docsCount: 4,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: true, grn: true, taxInvoice: true },
    budgetBefore: 450000,
    budgetAfter: 331350,
    date: '2026-08-06',
  },
  {
    id: '4',
    code: 'PV-2026-00483',
    title: 'Fuel & site consumables — Adama Logistics',
    project: 'Adama Logistics Park',
    costCode: 'CC-1050 · Fuel & Lubricants',
    payee: 'NOC Ethiopia',
    amount: 42900,
    method: 'Petty cash',
    status: 'ready_for_approval',
    preparedBy: 'Leta Girma',
    assignedApprover: 'dembi',
    docsCount: 4,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: true, grn: true, taxInvoice: true },
    budgetBefore: 95000,
    budgetAfter: 52100,
    date: '2026-08-07',
  },
  {
    id: '5',
    code: 'PV-2026-00485',
    title: 'Site generator diesel — CMC Residential Ph.2',
    project: 'CMC Residential Phase 2',
    costCode: 'CC-1050 · Fuel & Lubricants',
    payee: 'Total Ethiopia',
    amount: 8300,
    method: 'Petty cash',
    status: 'pending_docs',
    preparedBy: 'Leta Girma',
    assignedApprover: 'dembi',
    docsCount: 1,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: false, grn: false, taxInvoice: false },
    budgetBefore: 30000,
    budgetAfter: 21700,
    date: '2026-08-07',
  },
  {
    id: '6',
    code: 'PV-2026-00470',
    title: 'Excavator hire — Bole Ring Road',
    project: 'Bole Ring Road Extension',
    costCode: 'CC-5002 · Plant Hire',
    payee: 'Habesha Plant Rentals',
    amount: 224000,
    method: 'RTGS',
    status: 'paid',
    preparedBy: 'Leta Girma',
    assignedApprover: 'dembi',
    docsCount: 4,
    totalDocsRequired: 4,
    docsAttached: { po: true, proforma: true, grn: true, taxInvoice: true },
    budgetBefore: 500000,
    budgetAfter: 276000,
    date: '2026-08-03',
  },
];

export const VENDOR_QUOTES: VendorQuote[] = [
  {
    id: 'v1',
    name: 'Selam Steel PLC',
    location: 'Addis Ababa · 6 yrs on file',
    tenureOnRecord: '6 years',
    leadTimeDays: 5,
    advanceRequirement: '50% advance',
    onTimeRatio: '11/12 on-time',
    pricePerUnit: 71.60,
    unit: 'ETB per kg',
    isBestValue: true,
  },
  {
    id: 'v2',
    name: 'Kality Metal Works',
    location: 'Addis Ababa · 3 yrs on file',
    tenureOnRecord: '3 years',
    leadTimeDays: 3,
    advanceRequirement: '30% advance',
    onTimeRatio: '8/9 on-time',
    pricePerUnit: 74.20,
    unit: 'ETB per kg',
    isBestValue: false,
  },
  {
    id: 'v3',
    name: 'Habesha Steel Traders',
    location: 'Adama · 2 yrs on file',
    tenureOnRecord: '2 years',
    leadTimeDays: 9,
    advanceRequirement: 'Full advance',
    onTimeRatio: '5/8 on-time',
    pricePerUnit: 69.90,
    unit: 'ETB per kg',
    isBestValue: false,
  },
];

export const PEACHTREE_QUEUE: PeachtreeEntry[] = [
  { id: 'p1', period: 'June 2026', linesCount: 312, exportDate: '2026-07-02', status: 'Synced' },
  { id: 'p2', period: 'July 2026', linesCount: 288, exportDate: '2026-08-01', status: 'Synced' },
  { id: 'p3', period: 'August 2026 (in progress)', linesCount: 94, exportDate: null, status: 'Pending' },
];

export const CLIENT_CONTRACTS: ClientMilestoneContract[] = [
  {
    id: 'c1',
    name: 'Bole Ring Road Extension',
    contractValue: 42000000,
    billingType: 'Milestone Billing',
    statusText: 'On schedule',
    statusType: 'good',
    milestones: [
      { name: 'Mobilisation', progressPercent: 100, status: 'completed' },
      { name: 'Earthworks', progressPercent: 100, status: 'completed' },
      { name: 'Base course', progressPercent: 64, status: 'active' },
      { name: 'Asphalt', progressPercent: 0, status: 'pending' },
      { name: 'Handover', progressPercent: 0, status: 'pending' },
    ],
  },
  {
    id: 'c2',
    name: 'CMC Residential Phase 2',
    contractValue: 18600000,
    billingType: 'Milestone Billing',
    statusText: 'Overdue Br 480,000 (34 days)',
    statusType: 'bad',
    milestones: [
      { name: 'Mobilisation', progressPercent: 100, status: 'completed' },
      { name: 'Substructure', progressPercent: 100, status: 'completed' },
      { name: 'Superstructure', progressPercent: 100, status: 'overdue' },
      { name: 'Finishes', progressPercent: 20, status: 'active' },
      { name: 'Handover', progressPercent: 0, status: 'pending' },
    ],
  },
];

export const INITIAL_TAX_DECLARATION: TaxDeclaration = {
  period: 'July 2026',
  dueDate: '11 August 2026 (in 4 days)',
  tin: '0012-3456-78',
  totalSales: 10780000,
  totalPurchases: 6214300,
  outputVat: 1617000,
  inputVat: 932145,
  netVatPayable: 686355,
  isReviewed: false,
};
